name: log_box_navigation_logger
description: "Log Box extension for Navigation"
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.29.3"

dependencies:
  flutter:
    sdk: flutter

  json_annotation: ^4.9.0

  log_box:
    git:
      url: https://github.com/robzimpulse/log_box.git
      ref: master
      path: packages/log_box

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.3.3
  json_serializable: ^6.6.1